# Generated by Django 3.0 on 2021-09-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeofday', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='greeting',
            name='timeofday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.TimeOfDay'),
        ),
    ]
